owner: vevetron
repo: upptime

sites:
  - name: Metabase
    url: https://metabase.dds.dot.ca.gov
  - name: Metabase Staging
    url: https://metabase-staging.dds.dot.ca.gov
  - name: Analysis
    url: https://analysis.dds.dot.ca.gov
  - name: Analysis Staging
    url: https://analysis-staging.dds.dot.ca.gov
  - name: Reports
    url: https://reports.dds.dot.ca.gov
  - name: Reports Staging
    url: https://reports-staging.dds.dot.ca.gov
  - name: dbt Docs
    url: https://dbt-docs.dds.dot.ca.gov
  - name: dbt Docs Staging
    url: https://dbt-docs-staging.dds.dot.ca.gov
  - name: GTFS
    url: https://gtfs.dds.dot.ca.gov
  - name: Cal-ITP
    url: https://www.calitp.org
  - name: Test Site
    url: https://this-site-does-not-exist-123456.com

status-website:
  name: Cal-ITP Sites uptime monitor
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/vevetron/upptime

notifications:
  - type: slack
    webhook: $NOTIFICATION_SLACK_WEBHOOK_URL
